[".config/awesome/collision"]
  type = "git-repo"
  url = "https://github.com/Elv13/collision"
  
[".config/awesome/awesome-wm-widgets"]
  type = "git-repo"
  url = "https://github.com/streetturtle/awesome-wm-widgets"
