#!/bin/sh

echo "xinit before xinitrc-common: $DBUS_SESSION_BUS_ADDRESS"
. /etc/X11/xinit/xinitrc-common

echo "xinit before setting dbus addres: $DBUS_SESSION_BUS_ADDRESS" | systemd-cat
# workaround of bug https://bugzilla.redhat.com/show_bug.cgi?id=1622259
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
echo "xinit after setting dbus addres: $DBUS_SESSION_BUS_ADDRESS" | systemd-cat

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

export editor=nvim

export fmod_alsa_device=pulse

xrdb -merge $home/.xresources

xsetroot -cursor_name left_ptr

xset -dpms s off

setxkbmap -layout us -variant altgr-intl

xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock &

fcitx5 &

if [ -x /usr/bin/nm-applet ] ; then
    nm-applet --sm-disable &
fi

xhost +si:localuser:$USER

kdwalletd5 &
export ssh_auth_sock

redshift -l 50.73438:7.09549 &
flameshot &
volumeicon &
clipcatd &
sxhkd &
nextcloud &

awesome
