# TODO: This is device specific
preload=/home/kmies/wallpaper.png
wallpaper=HDMI-A-1,/home/kmies/wallpaper.png
wallpaper=HDMI-A-2,/home/kmies/wallpaper.png
wallpaper=DVI-D-1,/home/kmies/wallpaper.png
