# ============================================= #
# Start with defaults from the Sensible plugin  #
# --------------------------------------------- #
run-shell sensible.tmux
# ============================================= #

set  -g default-terminal "screen-256color"
set  -g base-index      1
setw -g pane-base-index 1
# We need to set default-shell before calling new-session
set  -g default-shell "/nix/store/hqw981c0vig48m2v6xyn4m1ixnqr0lk1-xonsh-0.19.9/bin/xonsh"

new-session

set -g status-keys vi
set -g mode-keys   vi

set  -g mouse             off
set  -g focus-events      off
setw -g aggressive-resize off
setw -g clock-mode-style  24
set  -s escape-time       0
set  -g history-limit     2000

source-file theme.conf

set -ga terminal-overrides ",xterm-256color*:RGB"
